//  用户
export const GET_USERS_MESSAGE = "GET_USERS_MESSAGE";
export const REMOVE_USERS_MESSAGE = "REMOVE_USERS_MESSAGE";
// 商品
export const GET_CATEGORIES_MESSAGE = "GET_CATEGORIES_MESSAGE";
export const ADD_CATEGORY_MESSAGE = "ADD_CATEGORY_MESSAGE";
export const UPDATE_CATEGORY_MESSAGE = "UPDATE_CATEGORY_MESSAGE";
export const DELETE_CATEGORY_MESSAGE = "DELETE_CATEGORY_MESSAGE";
//  角色
export const GET_ROLES_MESSAGE = "GET_ROLES_MESSAGE";
export const ADD_ROLES_MESSAGE = "ADD_ROLES_MESSAGE";
export const UPDATE_ROLES_MESSAGE = "UPDATE_ROLES_MESSAGE";
